[project]
name = "celery-task-metadata-persistence"
version = "0.1.0"
description = "Demo app with Celery and FastAPI."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.4.0",
    "fastapi>=0.115.6",
    "pymongo>=4.10.1",
    "redis>=5.2.1",
]
